name: Build Cork

on:
  push:
    branches: main
    tags:
      - '*'

jobs:
  build-app:
    runs-on: macos-13

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Xcodebuild
        run: xcodebuild -project Cork.xcodeproj -scheme Cork -destination platform=macOS build -derivedDataPath ./build
      
      - name: Create zip file
        run: cp -r build/Build/Products/Debug/Cork.app . && zip -r Cork.zip Cork.app

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.TOKEN }}
      #     file: Cork.zip
